### ISSUE TITLE
Search for company or package should be case insensitive

### ISSUE THREAD

**Issue by juliaferraioli** [FOSSRIT/FOCUSED-Web-Scraper#1]
At the moment, searching for:

`/dependencies/package/openssl`

returns nothing, but searching for:

`/dependencies/package/OpenSSL`

returns results. All searches should be case insensitive.

**Comment by MoralCode** [comment]
Looks to me like [this](https://github.com/FOSSRIT/FOCUSED-Web-Scraper/blob/1d2712804a3be08189a81240a2e3c0ed2c7cd5fa/webapp/app.py#L38) is where the url parameter is read

although if the database is storing them as case sensitive, that may require changes to the [code that inserts  dependencies into the DB](https://github.com/FOSSRIT/FOCUSED-Web-Scraper/blob/1d2712804a3be08189a81240a2e3c0ed2c7cd5fa/utils/database.py#L58) (and possibly a script to migrate/transform any existing db records).

Another solution could be to just adjust [the queries that control how the results are fetched from the database](https://github.com/FOSSRIT/FOCUSED-Web-Scraper/blob/1d2712804a3be08189a81240a2e3c0ed2c7cd5fa/webapp/database.py) to [perform case insensitive lookups](https://stackoverflow.com/a/16082874/)

overall seems like a pretty straightforward issue
